# -*- coding: utf-8 -*-
"""Salinan dari Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUG6JpOb1hW1IEAEsnxzZq6wrkd4CYr-

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** [Setia Nurrohman]
- **Email:** [cdcc229d6y1460@devacademy.id]
- **ID Dicoding:** [CDCC229D6Y1460]

## Menentukan Pertanyaan Bisnis

- Bagaimana Tren Penggunaan Sepeda dari Waktu ke Waktu (bulanan)?
- Kapan Waktu Paling Ramai Penggunaan Sepeda dalam Sehari?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

day_df=pd.read_csv('day.csv',sep=';')
hour_df=pd.read_csv('hour.csv',sep=';')

"""**Insight:**
- day_df Memiliki 731 baris dan 16 kolom. Data ini berisi ringkasan informasi penyewaan sepeda dalam skala harian.
- hour_df Memiliki 17.379 baris dan 17 kolom. Data ini lebih detail dalam merangkum informasi karena mencatat penggunaan sepeda setiap jam.
- Data sudah cukup lengkap untuk mencakup variabel waktu (hari, jam, musim), kondisi cuaca, dan jumlah pengguna (casual vs registered).

### Assessing Data
"""

day_df.info()
hour_df.info()

day_df.isna().sum()
hour_df.isna().sum()

print('Jumlah data duplikat:', day_df.duplicated().sum())

"""**Insight:**
- Kolom *dteday* terdeteksi sebagai kolom dengan tipe *object*. ini dapat menjadi masalah dikarenakan data tanggal harusnya bertipe *datetime* agar bisa diolah untuk analisis waktu.
- Tidak ditemukan data kosong (0 *null values*) pada semua kolom dalam data, hal ini berarti dataset tersebut tidak memuat *Missing Values*
- Kolom lain seperti *temp, atemp*, dan lain lain sudah dinormalisasi (dalam rentang antara 0 sampai 1)
- Tidak ada data yang terduplikasi dalam dataset (0 *duplicates*)

### Cleaning Data
"""

day_df['dteday']=pd.to_datetime(day_df['dteday'],format="%d/%m/%Y")
hour_df['dteday']=pd.to_datetime(hour_df['dteday'],format="%d/%m/%Y")
season_map= {
    1: 'Spring',
    2: 'Summer',
    3: 'Fall',
    4: 'Winter'
}
day_df['season'] = day_df['season'].map(season_map)

"""**Insight:**
- Mengubah kolom *dteday* dari *object* menjadi tipe *datetime* menggunakan *fungsi pd.to_datetime()* untuk menghindari masalah.
- Mengubah angka-angka pada kolom (1->*Spring*, dan seterusnya).
- Setelah melalui proses ini, data sudah bersih dan kolom waktu sudah dapat digunakan untuk melihat tren waktu.

## Exploratory Data Analysis (EDA)

### Explore ...
"""

day_df.describe()

hour_df.describe()

seasonrent=day_df.groupby('season')['cnt'].mean().sort_values(ascending=False)
seasonrent

hourrent=hour_df.groupby('hr')['cnt'].mean()
hourrent

"""**Insight:**
- Pada dataset *day_df*, rata-rata harian pengguna *registered* adalah 3656, sedangkan *casual* hanya 848. Kemudian pada dataset *hour_df*, rata-rata pengguna *registered* adalah 153 dan *casual* hanya 35. Hal ini membuktikan bisnis ini dipengaruhi oleh pelanggan tetap (*registered*).
- Total penyewa di tahun 2012 yang berjumlah 2.049.576, jauh lebih tinggi dibanding 2011 yang hanya berjumlah 1.243.103.
- Rata-rata penyewaan tertinggi terjadi pada musim gugur (*Fall*), hal ini dibuktikan dengan angka penyewaan di atas 5000 unit per hari.
- Data juga menunjukkan bahwa penyewaan sepeda paling banyak terjadi pada musim gugur yang berkorelasi dengan keadaan dimana suasana hangat sesuai untuk bersepeda.

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

monthly = day_df.resample('M', on='dteday')['cnt'].mean()

# ubah ke format nama bulan
monthly.index = monthly.index.strftime('%b %Y')

plt.figure(figsize=(12, 10))
plt.plot(monthly.index, monthly.values,marker='o')
plt.xticks(rotation=45)
plt.title("Tren Penggunaan Sepeda per Bulan")
plt.xlabel("Bulan")
plt.ylabel("Rata-rata Pengguna")
plt.grid(True)
plt.show()

"""### Pertanyaan 2:"""

hourly = hour_df.groupby('hr')['cnt'].mean()

plt.figure(figsize=(12, 10))
plt.plot(hourly.index, hourly.values,marker='o')
plt.title("Pola Penggunaan Sepeda per Jam")
plt.xlabel("Jam")
plt.ylabel("Rata-rata Pengguna")
plt.grid(True)
plt.show()

"""**Insight:**
- Grafik untuk Pertanyaan 1 menunjukkan pergerakan naik-turun (fluktuasi) setiap bulan. Dimulai dari bulan januari 2011 dengan rata-rata lebih dari seribu orang, kemudian puncak kenaikan jumlah penyewa ada di bulan juni dengan penyewa lebih dari 4000, tren ini terus berlanjut selama pertengahan tahun di antara bulan juni sampai september tepatnya saat musim gugur. Sedangkan penurunan jumlah penyewa biasanya terjadi di akhir tahun atau mendekati musim dingin. Pada grafik juga ditunjukkan kenaikan yang cukup signifikan dari penyewa sepeda pada tahun 2011 (total 1.243.102) dibandingkan dengan tahun 2012 (total 2.049.576).
- Grafik untuk pertanyaan 2 menunjukkan bahwa waktu (jam) juga berpengaruh terhadap jumlah penyewa sepeda pada hari tersebut. Penurunan mencapai titik terendah saat dini hari tepatnya pukul 2 sampai pukul 4 pagi (kurang dari 100 penyewa), kemudian naik sangat pesat ketika pukul 8 pagi (lebih dari 300 penyewa). Lonjakan drastis kedua terjadi saat sore hari pukul 17 sampai pukul 18 (lebih dari 400 penyewa), kemudian semakin menurun seiring waktu berjalan menuju pagi hari.

## Analisis Lanjutan (Opsional)
"""

weekday = day_df.groupby('workingday')['cnt'].mean()

plt.figure()
weekday.plot(kind='bar')
plt.title("Perbandingan Hari Kerja vs Libur")
plt.show()

"""## Conclusion

- Berdasarkan analisis tren bulanan dari tahun 2011 hingga 2012, dapat disimpulkan bahwa terjadi pertumbuhan yang konsisten, yaitu kenaikan jumlah penyewa yang signifikan dari tahu pertama ke tahun kedua, hal ini menunjukkan layanan penyewaan sepeda semakin diterima dan populer di masyarakat. Tren ini juga memiliki pola musiman yang kuat, dimana penggunaan sepeda mencapai puncaknya pada pertengahan tahun, yaitu antara bulan juni hingga september (musim panas menuju musim gugur). Lalu penyewaan mengalami penurunan drastis pada bulan desember, januari, dan februari. Hal ini berkorelasi langsung dengan musim dingin dan kondisi cuaca yang tidak mendukung untuk bersepeda. Dengan demikian, perusahaan penyewaan sepeda dapat merencanakan kampanye pemasaran yang lebih besar mulai bulan maret untuk bersiap menyambut lonjakan permintaan di pertengahan tahun, kemudian memaksimalkan operasional pada saat terjadi lonjakan jumlah penyewa sepeda.
- Berdasarkan analisis data per jam, waktu penggunaan sepeda menunjukkan pola yang sangat spesifik, yaitu pada Jam Sibuk Pagi (Peak Morning) terjadi lonjakan tajam tepatnya pada pukul 08.00. Ini menunjukkan bahwa mayoritas pengguna (terutama tipe registered) menggunakan sepeda sebagai transportasi untuk berangkat bekerja atau sekolah. Kemudian pada Jam Sibuk Sore (Peak Evening) terjadi  puncak penggunaan tertinggi dalam sehari, yaitu antara pukul 17.00 hingga 18.00. Pola ini mencerminkan arus pulang kerja atau sekolah. Selain itu, terjadi juga perbedaan perilaku. Pada hari kerja, puncak terjadi di jam sibuk (komuter). Namun, pada akhir pekan, penggunaan cenderung lebih merata dari siang hingga sore hari, yang menunjukkan pergeseran fungsi sepeda untuk tujuan rekrasi atau sekedar berolahraga. Dengan demikian, perusahaan penyewaan sepeda dapat memastikan ketersediaan unit sepeda dan kondisi teknis yang prima di titik-titik transportasi (stasiun/halte) pada waktu puncak yaitu pukul 07.00-09.00 dan pukul 16.00-19.00 untuk menghindari penumpukan antrean atau kehabisan stok.
"""